#ESPHome Base Configuration for PebblePower1

substitutions:
  device_name: pebblepower1
  friendly_name: PebblePower1
  icon: "mdi:switch"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  # Adds MAC address to device name to ensure unique name
  name_add_mac_suffix: true
  project:
    name: "PebbleTek.PebblePower1"
    version: "1.0.0"

esp32:
  board: "esp32-c6-devkitc-1"
  variant: "ESP32C6"
  flash_size: 8MB
  framework:
    platform_version: https://github.com/stintel/platform-espressif32#esp32-c6-test
    #platform_version: https://github.com/platformio/platform-espressif32.git
    type: esp-idf
    version: 5.1.0
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: "12345678"

captive_portal:

# Web Server
web_server:
  port: 80
  version: 2

# Time is needed to support functions such as total_daily_energy
# TODO: Alternative time source needs to be investigated
time:
  - platform: homeassistant
    id: homeassistant_time

i2c:

  # i2c internal bus for INA3221 and other optional devices
  - id: i2c_internal
    sda: 2
    scl: 3
    scan: true
    # frequency: 400kHz

  # i2c external bus for optional devices
  - id: i2c_external
    sda: 6
    scl: 7
    scan: true

switch:
  # Relay CH1
  - platform: gpio
    pin: 22
    id: CH1_relay
    name: ${friendly_name} Relay CH1
    icon: "mdi:electric-switch"

binary_sensor:
  # Relay CH1 onboard toggle button
  - platform: gpio
    pin:
      number: 8
      inverted: true
      mode:
        input: true
        pullup: true
    name: ${friendly_name}" Relay Button"
    on_press:
      - switch.toggle: CH1_relay

  # Relay CH1 external switch
  - platform: gpio
    pin:
      number: 18
      inverted: true
      mode:
        input: true
        pullup: true
    name: ${friendly_name}" Relay Switch"
    on_press:
      - switch.toggle: CH1_relay

  # FUNC Button
  # TODO: The timing and debounce filters need refining
  - platform: gpio
    pin:
      number: 5
      mode:
        input: true
        pullup: true
    id: sensorid1
    filters:
      - delayed_on_off: 80ms # Debounce filter to eliminate random false switching. 
    on_state:
      then:
        - binary_sensor.template.publish:
            id: switch_clicker
            state: ON
        - delay: 100ms
        - binary_sensor.template.publish:
            id: switch_clicker
            state: OFF

  - platform: template
    id: switch_clicker
    on_multi_click:
      - timing:
        - ON for at most 0.5s
        - OFF for at least 0.5s
        then:
          - logger.log: "Single Click"
          - lambda: |-
              if (id(template_sensor_1).state) {
              id(template_sensor_1).publish_state(false);
              } else { 
              id(template_sensor_1).publish_state(true);
              }

      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - logger.log: "Double Click"
          - lambda: |-
              if (id(template_sensor_2).state) {
              id(template_sensor_2).publish_state(false);
              } else {
              id(template_sensor_2).publish_state(true); 
              }

      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - logger.log: "Triple Click"
          - lambda: |-
              if (id(template_sensor_3).state) {
              id(template_sensor_3).publish_state(false);
              } else {
              id(template_sensor_3).publish_state(true); 
              }

  - platform: template
    name: Function 1 $friendly_name
    id: template_sensor_1
  - platform: template
    name: Function 2 $friendly_name
    id: template_sensor_2
  - platform: template
    name: Function 3 $friendly_name
    id: template_sensor_3

sensor:
  # Relay CH1 Power Daily Monitoring    
  - platform: total_daily_energy
    name: "PebblePower1 CH1 Daily Energy"
    power_id: power1
    id: my_power1

  # Core Power Daily Monitoring
  - platform: total_daily_energy
    name: ${friendly_name} Core Daily Energy
    power_id: power
    id: my_power

  # Internal INA3221 Power Monitoring
  - platform: ina3221
    i2c_id: i2c_internal
    address: 0x40

    # CH1 Power Monitoring
    channel_1:
      shunt_resistance: 0.015 ohm
      current:
        name: ${friendly_name} CH1 Current
        id: current1
      power:
        name: ${friendly_name} CH1 Power
        id: power1
      bus_voltage:
        name: ${friendly_name} CH1 Bus Voltage
        id: voltage1
      shunt_voltage:
        name: ${friendly_name} CH1 Shunt Voltage
        id: shunt_voltage1
        unit_of_measurement: "mV"

    # Core Power Monitoring
    channel_2:
      shunt_resistance: 0.15 ohm
      current:
        name: ${friendly_name} Core Current
        id: current
      power:
        name: ${friendly_name} Core Power
        id: power
      bus_voltage:
        name: ${friendly_name} Core Bus Voltage
        id: voltage
      shunt_voltage:
        name: ${friendly_name} Core Shunt Voltage
        id: shunt_voltage
        unit_of_measurement: "mV"

    # TODO: Investigate alternative update options and impacts
    update_interval: 1s
