substitutions:
  device_name: pebblepower8
  friendly_name: PebblePower8
  icon: "mdi:switch"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: "PebbleTek.PebblePower8"
    version: "1.0.0"

esp32:
  board: "esp32-c6-devkitc-1"
  variant: "ESP32C6"
  flash_size: 4MB
  framework:
    platform_version: 6.6.0
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
    type: esp-idf
    version: 5.2.1

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: "12345678"

captive_portal:

web_server:
  port: 80
  version: 2

time:
  - platform: homeassistant
    id: homeassistant_time

i2c:
  sda: 21
  scl: 22
  scan: true

mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20

binary_sensor:
  - platform: gpio
    pin: GPIO8
    name: "Button 1"
    on_press:
      then:
        - light.toggle: my_neopixel
  - platform: gpio
    pin: GPIO10
    name: "Button 2"
  - platform: gpio
    pin: GPIO13
    name: "Button 3"
  - platform: gpio
    pin: GPIO0
    name: "Button 4"
  - platform: mcp23017
    mcp23017: mcp23017_hub
    pin: 8
    name: "Button 5"
  - platform: mcp23017
    mcp23017: mcp23017_hub
    pin: 9
    name: "Button 6"
  - platform: mcp23017
    mcp23017: mcp23017_hub
    pin: 10
    name: "Button 7"
  - platform: mcp23017
    mcp23017: mcp23017_hub
    pin: 11
    name: "Button 8"

switch:
  - platform: gpio
    pin: GPIO22
    name: "Relay 1"
  - platform: gpio
    pin: GPIO23
    name: "Relay 2"
  - platform: gpio
    pin: GPIO15
    name: "Relay 3"
  - platform: gpio
    pin: GPIO1
    name: "Relay 4"
  - platform: mcp23017
    mcp23017: mcp23017_hub
    pin: 0
    name: "Relay 5"
  - platform: mcp23017
    mcp23017: mcp23017_hub
    pin: 1
    name: "Relay 6"
  - platform: mcp23017
    mcp23017: mcp23017_hub
    pin: 2
    name: "Relay 7"
  - platform: mcp23017
    mcp23017: mcp23017_hub
    pin: 3
    name: "Relay 8"

sensor:
  - platform: ina3221
    address: 0x40
    shunt_resistance: 0.005
    channel_1:
      name: "INA3221 Channel 1 Current"
    channel_2:
      name: "INA3221 Channel 2 Current"
    channel_3:
      name: "INA3221 Channel 3 Current"
  - platform: ina3221
    address: 0x41
    shunt_resistance: 0.005
    channel_1:
      name: "INA3221 Channel 4 Current"
    channel_2:
      name: "INA3221 Channel 5 Current"
    channel_3:
      name: "INA3221 Channel 6 Current"
  - platform: ina3221
    address: 0x42
    shunt_resistance: 0.075
    channel_1:
      name: "INA3221 Channel 7 Current"
    channel_2:
      name: "INA3221 Channel 8 Current"
    channel_3:
      name: "Board Power Current"

output:
  - platform: ledc
    pin: GPIO4
    id: neopixel_output

light:
  - platform: neopixel
    name: "NeoPixel Light"
    pin: GPIO4
    num_leds: 9
    id: my_neopixel