# This is the PebblePower ESPHome code base and is structured such that common elements 
# remain consistant and device specific content uses sequenced packages and includes to get
# the target code for the device being deployed.

# Please manage the commented lines below based on the device and or modules
# you are configuring for your PebblePower device.


##############################
# Board Configuration Section
##############################
substitutions:
  # These labels can be changed to anything you like and are reused through the code
  device_name: pebblepower12
  friendly_name: PebblePower12

  # This is very important and the whole firmware will not work if this is not set correctly. 
  # Please set as one of the following: PebblePower1, PebblePower2, PebblePower4, PebblePower8, PebblePower12
  device_type: PebblePower12

  # ESPHome doesn't allow for dynamic MQTT topics and so if you want to uniquely identify your 
  # device you can add the unique MAC id below. You can discover your boards MAC using "esptool flash_id"
  # to install esptool us "pip install esptool"
  mac: 6592f8

  # MQTT Broker
  mqtt_broker: 192.168.1.85


  ### Define Relay Channel Names
  # These labels can be changed to anything you like and are reused through the code
  CH1_name: chan1
  CH2_name: chan2
  CH3_name: chan3
  CH4_name: chan4
  CH5_name: chan5
  CH6_name: chan6
  CH7_name: chan7
  CH8_name: chan8
  CH9_name: chan9
  CH10_name: chan10
  CH11_name: chan11
  CH12_name: chan12

packages:
  common: !include common/common.yaml

  # Please update the <X> below with your PebblePower device type. 
  PebblePower: !include devices/PebblePower12.yaml
  
  # Please comment out this line if you are not using MQTT
  mqtt: !include common/mqtt.yaml

  # Please comment out this line if you are not using Home Assistant. It's important to remove if not
  # using home assistant as it will cause the device to reboot every 15 minutues if it can't connect to Home Assistant
  homeassistant: !include common/homeassistant.yaml

  # Some sensor code overwrites common code for items such as function button presses and therefore should 
  # always be the last packages to be loaded. 
  # Uncomment the lines below to enable your connected sensors.

  # Gyro: !include sensors/Gyro_MPU6050.yaml

logger:
  level: DEBUG


